weights: ''
cfg: models/yolov5s.yaml
data: data\data.yaml
hyp: data\hyps\hyp.scratch.yaml
epochs: 1000
batch_size: 32
imgsz: 224
rect: false
resume: 0
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 16
project: runs\train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 60
freeze: 0
save_period: -1
local_rank: -1
entity: true
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs\train\exp9
